### ISSUE TITLE
UNCAUGHT_EXCEPTION

### ISSUE THREAD

**Issue by arteck** [iobroker-community-adapters/ioBroker.pvforecast#101]
### The problem

```
25 May 2023 07:39:51.570
master host.iobroker: instance system.adapter.energiefluss-erweitert.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
25 May 2023 07:39:51.017
master zwave2.0: Node 74 is now awake
25 May 2023 07:39:50.999
master energiefluss-erweitert.0: Terminated (UNCAUGHT_EXCEPTION): Without reason
25 May 2023 07:39:50.995
master energiefluss-erweitert.0: Cannot read properties of undefined (reading 'id')
25 May 2023 07:39:50.995
master energiefluss-erweitert.0: TypeError: Cannot read properties of undefined (reading 'id') at EnergieflussErweitert.onStateChange (/opt/iobroker/node_modules/iobroker.energiefluss-erweitert/main.js:154:45) at EnergieflussErweitert.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5385:53) at processImmediate (node:internal/timers:466:21)
25 May 2023 07:39:50.991
master energiefluss-erweitert.0: uncaught exception: Cannot read properties of undefined (reading 'id') 
```

die kannst du Abfangen

**Comment by klein0r** [comment]
Ist nur ein ganz anderer Adapter?
